# Generated by Django 5.2.4 on 2026-09-20 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailcode',
            index=models.Index(fields=['purpose', 'email', 'created_at'], name='auth_email__purpose_10eecb_idx'),
        ),
    ]
